person:
  userName: "zhangshan \n wendy"
  # å•å¼•å· \n ä¼šä½œä¸ºå­—ç¬¦ä¸²è¾“å‡ºï¼›åŒå¼•å· \n ä¼šä½œä¸ºæ¢è¡Œç¬¦;  å•å¼•å·ä¼šè½¬ä¹‰ï¼ŒåŒå¼•å·ä¸ä¼šè½¬ä¹‰
  boss: true
  birth: 2019/02/02
  age: 18
#  interests: [ç¯®çƒï¼Œç¾½æ¯›çƒï¼Œè¶³çƒ]
  interests:
    - ç¯®çƒ
    - è¶³çƒ
  animal: [ é˜¿çŒ«ï¼Œé˜¿ç‹—]
  score: {englist:80, math:90}
  salarys: [9999.99,9999.08]
  pet:
    name: dog
    weight: 20.02
  allPets:
    sick:
      - {name: é˜¿ç‹—,weight: 20.22}
      - name: é˜¿å–µ
        weight: 2.02
      - name: å°è›‡
        weight: 1.01
    heath:
      - {name: é˜¿ğŸŒ¹,weight: 20.22}

